"use client";
import { FaLaravel, FaReact, FaHtml5, FaGithub, FaCss3, FaPhp, FaNodeJs, FaDocker } from "react-icons/fa";
import {
  SiJavascript,
  SiUnrealengine,
  SiTailwindcss,
  SiNextdotjs,
  SiBlender,
  SiGamedeveloper,
  SiTypescript,
  SiWhatsapp,
  SiCplusplus,
  SiEpicgames,
  SiGithub,
  SiMarkdown,
  SiDotnet,
  SiDiscord,
  SiDiscorddotjs,
  SiLaravel,
  SiHtml5,
  SiCss,
  SiVite,
  SiBootstrap,
  SiMysql,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";

const blankPlaceholder = 'https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg'

const projects = [
  {
    id: 0,
    image: [
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/portofolio/portfolio_thumbnail.webp"
    ],
    thumbnail: "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/portofolio/portfolio_thumbnail.webp",
    title: "Portfolio Website",
    sinopsis: "Personal Portfolio Website",
    description:
      "A personal portfolio website built with Next.js 16, React, and TypeScript. Features smooth page animations via Framer Motion, a typewriter hero section, paginated project showcase with modal viewer, contact form powered by EmailJS, and an ambient background music player. Media assets are hosted on Supabase Storage.",
    tags: ["React.js", "TypeScript", "Next.js", "Tailwind CSS", "Framer Motion", "EmailJS", "Supabase"],
    techIcons: [
      <FaReact />,
      <SiTypescript />,
      <SiNextdotjs />,
      <SiTailwindcss />,
      <SiJavascript />,
    ],
    date: "2025-04-12",
    liveUrl: null,
    repoUrl: "https://github.com/GorudenTaiga/portfolio",
  },
  {
    id: 1,
    image: [
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/videos/jelajah/jelajah_vid.webm",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr1.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr2.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr3.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr4.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr5.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr6.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr7.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr8.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr9.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr10.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr11.webp",
    ],
    thumbnail: "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/jelajah/scr1.webp",
    title: "Jelajah Nusantara",
    sinopsis: "Digital Representation of Indonesia",
    description:
      "Jelajah Nusantara is a game designed as a digital representation of Indonesia. In this game, players can explore the diversity of cultures, ethnicities, traditions, and unique characteristics from various regions across Indonesia. Powered by Unreal Engine 5, this game offers realistic graphics and immersive gameplay experiences.",
    tags: ["Unreal Engine 5", "Blender 3D", "Games", "Metahuman", "Sketchfab"],
    techIcons: [<SiUnrealengine />, <SiBlender />, <SiGamedeveloper />],
    date: "2023-04-28",
    liveUrl: null,
    repoUrl: null,
  },
  {
    id: 2,
    image: [
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/videos/litedex/litedex_cinematic.webm",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/litedex/litedex_thumbnail.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/litedex/litedex1.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/litedex/litedex2.webp",
    ],
    thumbnail: "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/litedex/litedex_thumbnail.webp",
    title: "LiteDex Protocol",
    sinopsis: "Cyber Security Game",
    description:
      "Litedex is a game where players act as hackers trying to break into a building called Litedex. Players must find creative ways to enter the building and retrieve important data from the Litedex company.",
    tags: ["Unreal Engine", "Blender 3D", "Games", "Metahuman"],
    techIcons: [<SiUnrealengine />, <SiBlender />, <SiGamedeveloper />],
    date: "2023-07-03",
    liveUrl: null,
    repoUrl: null,
  },
  {
    id: 3,
    image: [
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/videos/pendopo/pendopo_vid.webm",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/pendopo/pendopo1.webp",
      "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/pendopo/pendopo2.webp",
    ],
    thumbnail: "https://rqbcrttxfhxmcaxiropg.supabase.co/storage/v1/object/public/storage/images/pendopo/pendopo1.webp",
    title: "Pendopo",
    sinopsis: "A Virtual Space of Jogja’s traditional house",
    description:
      'A virtual space to showcase Jogja’s traditional house called "Pendopo." This was my very first project during my time at PT. Jivaloka Prasanna Sanasi.',
    tags: ["Unreal Engine", "Blender 3D", "Games", "Metahuman"],
    techIcons: [<SiUnrealengine />, <SiBlender />, <SiGamedeveloper />],
    date: "2023-02-28",
    liveUrl: null,
    repoUrl: null,
  },
  {
    id: 4,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "Perpustakaan Provinsi Papua",
    sinopsis: "Sistem Manajemen Perpustakaan Daerah Papua",
    description:
      "A full-featured regional library management system built for Perpustakaan Daerah Papua. Developed with Laravel 12, React (via Inertia.js), and Filament v4 as the admin panel. Features include member registration with document verification, digital book access via Google Drive, loan management with admin approval workflow, fine & sanction tracking, barcode generation for books and member cards, PDF export, and a pre-seeded catalog of 100 books across 10 categories. Containerized with Docker and deployed on Render.",
    tags: ["Laravel", "PHP", "React.js", "Inertia.js", "Tailwind CSS", "Filament", "Docker", "MySQL"],
    techIcons: [<FaLaravel />, <FaPhp />, <FaReact />, <SiTailwindcss />, <SiBootstrap />, <FaDocker />, <SiVite />, <SiMysql />],
    date: "2026-03-06",
    liveUrl: "https://perpustakaan-papua-laravel.onrender.com",
    repoUrl: "https://github.com/GorudenTaiga/perpustakaan-papua-laravel",
  },
  {
    id: 5,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "Belajar Laravel",
    sinopsis: "Laravel 12 + React Starter Kit dengan shadcn/ui",
    description:
      "A full-stack sandbox project built on the official Laravel React Starter Kit. Combines Laravel 12 with React (via Inertia.js), TypeScript, shadcn/ui component library, Ziggy for client-side routing, Prettier for code formatting, and Pest for testing. Used for exploring modern Laravel + React full-stack development patterns.",
    tags: ["Laravel", "PHP", "React.js", "Inertia.js", "TypeScript", "shadcn/ui", "Pest"],
    techIcons: [<FaLaravel />, <FaPhp />, <FaReact />, <SiTypescript />, <SiTailwindcss />, <SiVite />],
    date: "2025-07-02",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/belajar-laravel",
  },
  {
    id: 6,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "KSG Bot",
    sinopsis: "Bot Discord dengan fitur level, leaderboard, dan Pixiv",
    description:
      "A Discord bot built with discord.js v14, featuring a leveling and XP system with SQLite persistence, server leaderboard rankings, Pixiv artwork search and display via API integration, help menu, and utility commands (ping, level, leaderboard, pixiv). Uses Axios for HTTP requests and dotenv for environment configuration.",
    tags: ["Discord.js", "Node.js", "SQLite", "JavaScript", "Discord Bot", "Pixiv API"],
    techIcons: [<SiDiscord />, <FaNodeJs />, <SiJavascript />],
    date: "2025-05-21",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/ksg-bot",
  },
  {
    id: 8,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "WhatsApp Bot Baileys",
    sinopsis: "Bot WhatsApp berbasis Baileys dengan image processing",
    description:
      "A WhatsApp bot powered by @whiskeysockets/baileys v6, the leading unofficial WhatsApp Web API library. Features an Express.js HTTP server, image processing with Sharp, PM2 process manager for production deployment, node-cache for efficient caching, and a modular command structure.",
    tags: ["JavaScript", "Node.js", "Baileys", "WhatsApp", "Express.js", "PM2"],
    techIcons: [<SiJavascript />, <FaNodeJs />, <SiWhatsapp />],
    date: "2025-03-01",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/whatsappbot-baileys",
  },
  {
    id: 9,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "WhatsApp Bot",
    sinopsis: "Bot WhatsApp berbasis whatsapp-web.js dengan integrasi Pixiv",
    description:
      "A WhatsApp bot using whatsapp-web.js and Puppeteer for browser-based automation. Integrates Pixiv artwork search and download via pixiv-api-client, image processing with Sharp, PM2 for production deployment on Render, and an Express.js server for webhook handling.",
    tags: ["JavaScript", "Node.js", "WhatsApp Web.js", "Puppeteer", "Pixiv API", "Express.js"],
    techIcons: [<SiJavascript />, <FaNodeJs />, <SiWhatsapp />],
    date: "2025-02-15",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/whatsappbot",
  },
  {
    id: 10,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "Unreal Engine",
    sinopsis: "Fork dari Unreal Engine untuk modifikasi",
    description:
      "A fork of the Epic Games Unreal Engine repository for exploring game development, blueprint scripting, and engine customization.",
    tags: ["Unreal Engine", "C++", "Game Development", "Blueprint"],
    techIcons: [<SiUnrealengine />, <SiCplusplus />, <SiGamedeveloper />, <SiEpicgames />],
    date: "2024-01-15",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/UnrealEngine",
  },
  {
    id: 11,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "GorudenTaiga (Profile)",
    sinopsis: "GitHub Profile README dengan layout profesional",
    description:
      "A professionally designed GitHub profile README featuring tech stack badges, project highlights, GitHub statistics cards, contribution activity graphs, and social links. Redesigned with a clean professional layout using GitHub-readme-stats, shields.io badges, and profile widgets.",
    tags: ["GitHub Profile", "Markdown", "GitHub Stats", "README"],
    techIcons: [<SiGithub />, <SiMarkdown />],
    date: "2026-03-02",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/GorudenTaiga",
  },
  {
    id: 12,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "Speech",
    sinopsis: "Voice assistant desktop berbahasa Jepang",
    description:
      "A C# desktop voice assistant using Windows Speech Recognition and SpeechSynthesizer APIs. Responds in Japanese via the Microsoft Haruka TTS voice with time-aware greetings (ohayou/konnichiwa/konbanwa). Supports voice commands to launch and close applications including Osu!, Unreal Engine 5.2 & 5.3, OpenTabletDriver, VS Code, Chrome (multi-profile), and YouTube.",
    tags: ["C#", ".NET", "Speech Recognition", "Text-to-Speech", "Windows API", "Automation"],
    techIcons: [<TbBrandCSharp />, <SiDotnet />],
    date: "2024-06-07",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/speech",
  },
  {
    id: 13,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "Codewars Data Scraping",
    sinopsis: "Web scraper C# untuk ekstraksi data Codewars",
    description:
      "A C# web scraping utility (BelajarWebScraping) that extracts and processes coding challenge data from Codewars. Built with .NET and released as a standalone executable (v1.0.0). A learning project exploring web scraping techniques and data processing with C#.",
    tags: ["C#", ".NET", "Web Scraping", "Codewars", "Data Processing"],
    techIcons: [<TbBrandCSharp />, <SiDotnet />],
    date: "2024-05-07",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/CodewarsDataScraping",
  },
  {
    id: 14,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "Password Generator",
    sinopsis: "Utilitas generator password aman berbasis C#",
    description:
      "A C# console-based password generator utility built with .NET. Generates secure, customizable passwords with configurable options for length and character sets (uppercase, lowercase, numbers, symbols).",
    tags: ["C#", ".NET", "Security", "Utility", "Password Generator"],
    techIcons: [<TbBrandCSharp />, <SiDotnet />],
    date: "2024-05-04",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/passwordgenerator",
  },
  {
    id: 15,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "RPG UE5",
    sinopsis: "Game RPG dengan sistem combat dan animasi di UE5.2",
    description:
      "An RPG game project built with Unreal Engine 5.2, leveraging advanced animation plugins including Motion Warping, Animation Warping, AnimationLocomotionLibrary, and Pose Search for realistic character locomotion. Implements sword attack combo mechanics with hit sound effects and Blueprint-scripted combat animations.",
    tags: ["Unreal Engine 5.2", "Blueprint", "Game Development", "RPG", "Motion Warping", "C++"],
    techIcons: [<SiUnrealengine />, <SiGamedeveloper />, <SiEpicgames />, <SiCplusplus />],
    date: "2023-10-17",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/RPG_UE5",
  },
  {
    id: 22,
    image: [blankPlaceholder],
    thumbnail: blankPlaceholder,
    title: "Knick Knacks",
    sinopsis: "Aplikasi Pemesanan Makanan & Catering",
    description:
      "A full-stack food ordering and catering management web application built with Laravel 9 and Blade templating. Features a product catalog with a shopping cart (Keranjang), order & payment flow (Pembayaran), and dedicated catering package pages (Paket Nussa, Paket Elsa). Includes a complete admin panel for managing menu items and orders, user authentication via Laravel Sanctum, and separate role-based views for admin and customers.",
    tags: ["Laravel", "PHP", "Blade", "Sanctum", "MySQL", "Vite", "E-Commerce"],
    techIcons: [<FaLaravel />, <FaPhp />, <SiVite />, <SiMysql />],
    date: "2023-01-29",
    liveUrl: "",
    repoUrl: "https://github.com/GorudenTaiga/knick_knacks"
  },
];

export default projects;
